### ISSUE TITLE
Am getting B2RequestError 

### ISSUE THREAD

**Issue by therumbler** [james7132/aiob2#1]
```Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import aiob2
  File "/root/.local/share/virtualenvs/Siteifier-9I8jDYBV/lib/python3.7/site-packages/aiob2/__init__.py", line 1, in <module>
    from aiob2.b2 import B2
  File "/root/.local/share/virtualenvs/Siteifier-9I8jDYBV/lib/python3.7/site-packages/aiob2/b2.py", line 1, in <module>
    from aiob2.exceptions import B2ApplicationKeyNotSet, B2KeyIDNotSet
  File "/root/.local/share/virtualenvs/Siteifier-9I8jDYBV/lib/python3.7/site-packages/aiob2/exceptions.py", line 5, in <module>
    400: B2RequestError,
NameError: name 'B2RequestError' is not defined```

**Comment by WardPearce** [comment]
Might be worth checking out https://github.com/WardPearce/backblaze
